### ISSUE TITLE
Angular 13 / IonicSelectableModule does not have 'ɵmod' property

### ISSUE THREAD

**Issue by muhammed671** [ionic-selectable/ionic-selectable#370]
Hello,

i have some issues with integrating into ionic Angular 13

This is the issue:
core.mjs:6484 ERROR Error: Uncaught (in promise): Error: Type IonicSelectableModule does not have 'ɵmod' property.
Error: Type IonicSelectableModule does not have 'ɵmod' property.
    at getNgModuleDef (core.mjs:1130:15)
    at recurse (core.mjs:21739:21)
    at recurse (core.mjs:21750:17)
    at registerNgModuleType (core.mjs:21735:5)
    at new NgModuleFactory (core.mjs:21857:13)
    at Compiler.compileModuleSync (core.mjs:25061:16)
    at Compiler.compileModuleAsync (core.mjs:25067:37)
    at MergeMapSubscriber.project (router.mjs:3983:43)
    at MergeMapSubscriber._tryNext (mergeMap.js:44:1)
    at MergeMapSubscriber._next (mergeMap.js:34:1)
    at resolvePromise (zone.js:1255:1)
    at resolvePromise (zone.js:1209:1)
    at zone.js:1321:1
    at ZoneDelegate.invokeTask (zone.js:434:1)
    at Object.onInvokeTask (core.mjs:25463:33)
    at ZoneDelegate.invokeTask (zone.js:433:1)
    at Zone.runTask (zone.js:205:1)
    at drainMicroTaskQueue (zone.js:620:1)

The Versions are: 
ionic version 6.17.1
npm version 6.14.8

"dependencies": {
    "@angular/common": "~13.0.0",
    "@angular/core": "~13.0.0",
    "@angular/forms": "~13.0.0",
    "@angular/platform-browser": "~13.0.0",
    "@angular/platform-browser-dynamic": "~13.0.0",
    "@angular/router": "~13.0.0",
    "@capacitor/app": "1.1.0",
    "@capacitor/core": "3.4.0",
    "@capacitor/haptics": "1.1.4",
    "@capacitor/keyboard": "1.2.1",
    "@capacitor/status-bar": "1.0.7",
    "@hendt/ebay-api": "^5.3.0",
    "@ionic/angular": "^6.0.0",
    "ionic-selectable": "^4.9.0",
    "rxjs": "~6.6.0",
    "tslib": "^2.2.0",
    "zone.js": "~0.11.4"
  },

Is Ionic-Selctble compatible with Angular 13? How I can solve this issue?

**Comment by edy-ap** [comment]
thanks for you report, i check this

**Comment by toxaq** [comment]
Same problem. Is any one successfully using Angular 13 without downgrading or backward compiling their entire project?

**Comment by zolakt** [comment]
Same problem. Angular 13 introduced some breaking changes.

We want to use this lib in a new project, and starting it with an outdated angular version is just not an option.

Is there any ETA when will this lib become Angular 13 compatible?

**Comment by zolakt** [comment]
@edy-ap Is this lib maintained anymore? Angular is now at version 14, and this lib is still at version 11.
